### ISSUE TITLE
Specifically ‘Vanilla’ JS resources?

### ISSUE THREAD

**Issue by davidhund** [sorrycc/awesome-javascript#138]
I just started compiling a little list of–specifically–‘Vanilla’ Javascript resources: https://github.com/davidhund/awesome-vanilla

Before making a PR I'd like to ask if this could be a handy addition to your list-of-lists?

**Comment by huei90** [comment]
hmm.. I'm not sure where to put in.

**Comment by davidhund** [comment]
IDK, maybe in the ‘Other Awesome Lists’ section? But I agree it's of questionable value :stuck_out_tongue_winking_eye:

**Comment by huei90** [comment]
:smile:  Then It may be loops

awesome javascript -> awesome vanilla -> awesome javascript -> ....

welcome PR :beers:

**Comment by davidhund** [comment]
Ghehehe. Aren't all lists under ‘Other’ recursive then? :smile_cat:

**Comment by huei90** [comment]
Yes XD
