### ISSUE TITLE
Some quality control

### ISSUE THREAD

**Issue by hueitan** [sorrycc/awesome-javascript#143]
Perhaps we need some Quality control for the repo. Otherwise all the JavaScript related project can be PR here. JavaScript is a huge and this list can be spammed. :-1:

**Comment by Waterloo** [comment]
How about adding javascript with certain threshold of stars in github

**Comment by arthurvr** [comment]
> How about adding javascript with certain threshold of stars in github

Quality of something isn't the same as its popularity.

**Comment by huei90** [comment]
> Quality of something isn't the same as its popularity.
Agree with that.

@arthurvr what's your experience about the QC?

**Comment by arthurvr** [comment]
Making black-on-white rules about something like this is really difficult. The most important part is that you should try to be strict when merging PRs.

> Is the project still maintained? Does it have proper documentation? Is it well tested? Isn't the idea behind this project outdated? What's the use-case?

All of these never give a perfect view of a project, but are really good indicators. It's going to cause annoying discussions but you should try to be hard and say "no thanks" to more things.

Also, frequently read through the list yourself and remove everything which doesn't deserve there.

**Comment by Zhouzi** [comment]
Maybe you could make a small group of people/contributors to vote for each addition and accept the PR if the majority voted for it.

**Comment by huei90** [comment]
@Zhouzi still having the same problem that @arthurvr mentioned

> Quality of something isn't the same as its popularity.

**Comment by Zhouzi** [comment]
It would be up to the group of people you selected to review and judge of a suggestion's quality based on some criteria. However this might be a bit of work so I think the idea of @arthurvr is great. You can have some fixed rules and see if the PRs follow them.

**Comment by huei90** [comment]
No idea for now. Let's see.
