### ISSUE TITLE
Include stars?

### ISSUE THREAD

**Issue by bbirand** [sorrycc/awesome-javascript#180]
Is there  a way to easily incorporate the number of stars in the repos? This would make it much easier to browse large categories..

**Comment by patrick-steele-idem** [comment]
Sounds like a great idea for a Chrome Extension. Find all links to Github projects and insert number of stars next to each link.

**Comment by markogresak** [comment]
I was thinking of how I would do something similar for one of my readmes. The solution is basically the same as what build systems and other shield badges do: put up a rendering server which outputs an image or svg of current stars for given repo and add the image next to list item.

There is already a solution for that: http://githubbadges.com/. 
Here is the result for current repo: [![star this repo](http://githubbadges.com/star.svg?user=sorrycc&repo=awesome-javascript&style=flat)](https://github.com/sorrycc/awesome-javascript)

Or the one from [shields.io](http://shields.io/), but I'm not sure how to control the labels: [![GitHub stars](https://img.shields.io/github/stars/badges/shields.svg?style=social&label=Star)](https://github.com/sorrycc/awesome-javascript)

Although honestly, I'd prefer a simpler design, something like just a star and text, not the full badge.

**Comment by bbirand** [comment]
My thinking would be to regularly annotate the repo via a script? Say when the maintaners add updates.

For instance, here's an example that adds the star number at the end of the line:
https://github.com/bbirand/awesome-javascript/blob/master/README_annotated.md

The script I put together for doing it is here:
https://github.com/bbirand/awesome-augmenter

What do you guys think? Maybe having other measures than number of stars would also be useful. I usually also look at the time of the last commit, for instance..

**Comment by huei90** [comment]
Adding a number of star besides the repo link is annoying.

We do have the `badge` before but already remove it.
https://github.com/sorrycc/awesome-javascript/commit/ed27839300cf040381f8064b6a686cf9237d53f5

@patrick-steele-idem Using the Extension is good idea, but how should you handle the massive API request to Github, that is the problem.

**Comment by huei90** [comment]
I think if we define the [quality](https://github.com/sorrycc/awesome-javascript/issues/143) for this awesome list.

We don't need to worry about the **star** for every repo, there is already qualified.

**Comment by huei90** [comment]
Closed.
