### ISSUE TITLE
Merge two incredible lists

### ISSUE THREAD

**Issue by moacirosa** [sorrycc/awesome-javascript#198]
Today I was reading my Github timeline and a friend has starred an [incredible list named Essential Javascript Links](https://github.com/ericelliott/essential-javascript-links) by @ericelliott. Do you think that it would be possible to merge these two lists and concentrate content only in one place?

**Comment by ericelliott** [comment]
Maybe you should curate your own list, combining the best of the two. [The Value of Curation](https://medium.com/@jrigerl/the-value-of-curation-5847b24bfb78)

**Comment by huei90** [comment]
[essential-javascript-links](https://github.com/ericelliott/essential-javascript-links) provides great links too, unfortunately, I have no authority to do that.

Nice job @ericelliott

**Comment by huei90** [comment]
All I can do is, provide the external link to essential-javascript-links.

**Comment by ericelliott** [comment]
:+1:

**Comment by moacirosa** [comment]
First of all thanks @ericelliott for feedback and a really good text recommendation. For me make totally sense include the external link...

:+1:

**Comment by huei90** [comment]
:+1:

**Comment by ericelliott** [comment]
I would welcome a pull request to link to this list from Essential JavaScript Links. Some great library picks here. =)

:guitar:

**Comment by huei90** [comment]
welcome :guitar:
