### ISSUE TITLE
Section to Articles

### ISSUE THREAD

**Issue by pedropolisenso** [sorrycc/awesome-javascript#200]
a section to insert links of articles JavaScript?

**Comment by huei90** [comment]
How about this
https://github.com/sorrycc/awesome-javascript#worth-reading

**Comment by pedropolisenso** [comment]
Okay, but why not create a section to article/post?

**Comment by huei90** [comment]
Okay, you are welcome to create a new section for **Article/Post** :+1:

**Comment by pedropolisenso** [comment]
@huei90 ncie. Soon I will send a Pull Request. Thank you!

**Comment by huei90** [comment]
sure

**Comment by huei90** [comment]
wait for your pr

**Comment by pedropolisenso** [comment]
Ok!
