### ISSUE TITLE
Jquery Cookie Moved.

### ISSUE THREAD

**Issue by webcaetano** [sorrycc/awesome-javascript#231]
Hello guys?

https://github.com/carhartl/jquery-cookie 

Moved to 

https://github.com/js-cookie/js-cookie

Should i create a PR?

**Comment by huei90** [comment]
Although it officially move to js-cookie, but they have different interface. I would like to keep both instead of replace it.

**Comment by webcaetano** [comment]
Ok, i'll create a PR adding js-cookie and keep jquery-cookie.

**Comment by huei90** [comment]
Sure @webcaetano thank you.

**Comment by huei90** [comment]
DONE.
