### ISSUE TITLE
Add markItUp!

### ISSUE THREAD

**Issue by nodiscc** [sorrycc/awesome-javascript#347]
http://markitup.jaysalvat.com/home/
https://github.com/markitup/1.x
universal markup jQuery editor - supports Html, Textile, Wiki Syntax, Markdown, BBcode or your own markup

**Comment by gokaygurcan** [comment]
Hi @nodiscc,

it seems there's now https://github.com/markitup/2.x too. Closing this issue. If you want to add v2, you can always create a PR. 

Thanks!
