### ISSUE TITLE
Bower Deprecation Notice and recommendation to move to a different system

### ISSUE THREAD

**Issue by caraya** [sorrycc/awesome-javascript#417]
Bower indicates that while it's still being supported developers should move to WebPack or Yarn for any new projects. Should this be indicated in the list? If so how?

I was going to just do it but thought it'd be better to open an issue and discuss it before doing so.

**Comment by gokaygurcan** [comment]
Hi @caraya,

When someone you runs install command, they see the warning already. I believe there's no point to bloat the list with the warning that is as visible as possible. 

Thanks for the suggestion but closing the issue because this is not relevant to the purpose of the list.
