### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by nacimgoura** [sorrycc/awesome-javascript#438]
There have been no updates to the page since 2 months.
Is the page still maintained?

**Comment by kasiriveni** [comment]
@sorrycc  Please add Repository permission levels for an organization

**Comment by nacimgoura** [comment]
Still no commit done.
It's been 3 months without any updates.
If it continues I will continue this project on the fork I had done.

**Comment by hueitan** [comment]
@sorrycc please have a look for this issue

**Comment by danedavid** [comment]
137 PRs :disappointed:

**Comment by nacimgoura** [comment]
@sorrycc Is it possible to merge the pull request ?

**Comment by nacimgoura** [comment]
I think this project is dead. 😞

**Comment by kasiriveni** [comment]
:disappointed:

**Comment by hueitan** [comment]
It is difficult to define whether one project is dead, but I would say it is not dead yet.
