### ISSUE TITLE
Remove unmaintained projects

### ISSUE THREAD

**Issue by shrpne** [sorrycc/awesome-javascript#488]
I found few unmaintained parallax libraries:
stellar, skrollr.

Consider adding [rellax](https://github.com/dixonandmoe/rellax) instead.

**Comment by shrpne** [comment]
@gokaygurcan  Why wontfix? These packages are marked as unmaintained by their authors?
If you don't have time, I can make a PR to remove them.

https://github.com/Prinzhorn/skrollr
https://github.com/markdalgleish/stellar.js

**Comment by gokaygurcan** [comment]
I closed all PRs and issues older than 2020. No particular reason other than this.

Feel free to create a PR to remove them, thanks in advance!
