### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by Raiondesu** [sorrycc/awesome-javascript#504]
@sorrycc, there are more than a hundred PRs without a single comment, and the last accepted PR was about 2 months ago.

This got me thinking - is this repository abandoned or something?

**Comment by gokaygurcan** [comment]
Hi @Raiondesu,

Recently, someone requested to have more active maintainers to manage all the open PRs and stuff (see #517 for the original post). @andreasonny83 and myself volunteered to do this. And now the collaborators team doubled in size. I'm currently working on CI implementation to detect and fix dead URLs before merging them back to `master` branch. After that, I'll try to speed up the merging process too.

It'd be a shame to let this repository die with 15k stars and 1k watchers. So, no, it's not dead and it'll gain its speed slowly in the upcoming days.

**Comment by gokaygurcan** [comment]
Closing the issue because it's no longer relevant ;)
