### ISSUE TITLE
awesome tag

### ISSUE THREAD

**Issue by andreasonny83** [sorrycc/awesome-javascript#529]
@gokaygurcan please add the following tags to this repo: `awesome` `awesome-list` so it can easily appear in the GitHub search results for the Awesome repositories: https://github.com/topics/awesome

**Comment by gokaygurcan** [comment]
hey @andreasonny83, 
sadly, i cannot do that. only the owner of this repository can add those tags. sorry :(

**Comment by andreasonny83** [comment]
@gokaygurcan is it worth to keep this issue open?
Is there any change that @sorrycc is going to have a look at this any time soon?
