### ISSUE TITLE
search engine

### ISSUE THREAD

**Issue by cztomsik** [sorrycc/awesome-javascript#544]
Not sure if this is the best place but it's related. Some time ago I made a site where you can quickly search for javascript libraries. Unlike others, it sorts exclusively by stars and project activity. So if you're using github search instead of npmjs or yarnpkg you might give it a try and who knows, maybe you'll enjoy it and consider it a good addition to your list.

It's called [SearchLibs](http://searchlibs.com)

**Comment by rajsingha4520** [comment]
I am an Android developer. I read in class 12
I am very poor please help me with some money I have a computer with 2 gb ram and Intel process I developes app on it but it's hard to run ...so please donate me some money. Bank name - UCO Bank , MY Bank account number - 06570110036969 , Swift code - UCBAINBB102 , Ifsc code - UCBA0000657 , Account holder name - Raj Singha ..I am from India . Please donate as you like.

**Comment by andreasonny83** [comment]
That's good but a bit unrelated to this project.
