### ISSUE TITLE
codecrumbs - visual tool for learning a codebase

### ISSUE THREAD

**Issue by Bogdan-Lyashenko** [sorrycc/awesome-javascript#601]
Hi @sorrycc . My name is Bohdan and I am studying problems of reading code.
I just finished working on the first version of "codecrumbs"- visual tool for learning a codebase by putting breadcrumbs in a source code.
Check out [https://github.com/Bogdan-Lyashenko/codecrumbs](https://github.com/Bogdan-Lyashenko/codecrumbs) repo, it might be quite useful while digging into big codebase.
![image](https://user-images.githubusercontent.com/2098309/53086268-11b9ab00-3505-11e9-944b-575684c5c7f6.png)

Can you consider adding it to the list? Please let me know if I can create a PR. Thanks 🙂

**Comment by gokaygurcan** [comment]
Woa, that looks really nice! Good work!

**Comment by ahmedam55** [comment]
I love it @Bogdan-Lyashenko

**Comment by Bogdan-Lyashenko** [comment]
@gokaygurcan @ahmedam55 https://github.com/sorrycc/awesome-javascript/pull/602 here is PR 🙂 thanks a lot, appreciate that.
