### ISSUE TITLE
Add libraries that deal with querying within JSON

### ISSUE THREAD

**Issue by prashantk0001** [sorrycc/awesome-javascript#711]
can someone add this kind of libraries if they know the best ones? I came here to find one but didn't find any :/
JSPath, JSONPath etc

here's StackOverflow thread: https://stackoverflow.com/questions/8481380/is-there-a-json-equivalent-of-xquery-xpath

**Comment by gokaygurcan** [comment]
Hi,

I remember this one: https://github.com/aykutkardas/Json-Function

Do you think it's relevant?

**Comment by prashantk0001** [comment]
Yes!

**Comment by gokaygurcan** [comment]
Closing this one now, feel free to comment if you want to re-open. 
Thanks a lot!
