### ISSUE TITLE
**PAGE IS TOTALLY BROKEN UNTIL MY CHANGES ARE MERGED**

### ISSUE THREAD

**Issue by klutchdev** [sorrycc/awesome-javascript#719]
I took care of ALL formatting issues when I saw the page was completely broken. 
Please merge!

**Comment by gokaygurcan** [comment]
Thanks for taking care of the problem. It'll get merge as soon as possible. 
Next time, please keep the drama in a tolerable limits. No need to create an issue with all caps saying MY CHANGES WILL SAVE THE WORLD! 

Anyway, thanks again.

**Comment by klutchdev** [comment]
It wasn't supposed to come out like that lol. I had just worked 20 something hours, and when I saw this all broken I got a little upset because I love this page. No problem, sorry for the hassle 🍻🔥🤪
