### ISSUE TITLE
Snowpack?

### ISSUE THREAD

**Issue by jamesxv7** [sorrycc/awesome-javascript#756]
I find that Snowpack deserves to be on the bunderls list, I think it fits requirements on https://github.com/sorrycc/awesome-javascript/issues/731.

**Comment by gokaygurcan** [comment]
Hi,

Feel free to add it yourself, let's see how fast we accept and add it to the list it deserves to be in :) 

Cheers

**Comment by jamesxv7** [comment]
Excellent @gokaygurcan 

https://github.com/sorrycc/awesome-javascript/pull/758
