### ISSUE TITLE
How about adding a web-worker section?

### ISSUE THREAD

**Issue by KID-joker** [sorrycc/awesome-javascript#842]
like [partytown](https://github.com/BuilderIO/partytown), [comlink](https://github.com/GoogleChromeLabs/comlink), [greenlet](https://github.com/developit/greenlet), [workerize](https://github.com/developit/workerize), [threads.js](https://github.com/andywer/threads.js), [workly](https://github.com/pshihn/workly), [stockroom](https://github.com/developit/stockroom), [workerpool](https://github.com/josdejong/workerpool), [clooney](https://github.com/GoogleChromeLabs/clooney), etc.

**Comment by gokaygurcan** [comment]
It's a community driven repository. Feel free to add the section with relevant links and create a PR.
