### ISSUE TITLE
Add reading material?

### ISSUE THREAD

**Issue by mdecaffmeyer** [sorrycc/awesome-javascript#86]
Some other "awesome" lists have a list of books and other resources (tutorials, websites, ...) which have a high influence (or had but still worth reading).
e.g. 
Java: 
https://github.com/akullpp/awesome-java#influential-books
https://github.com/akullpp/awesome-java#websites
PHP: 
https://github.com/ziadoz/awesome-php#php-books
https://github.com/ziadoz/awesome-php#php-videos
https://github.com/ziadoz/awesome-php#php-reading
https://github.com/ziadoz/awesome-php#php-websites
https://github.com/ziadoz/awesome-php#other-websites

It would be nice to have such a list of books/tutorials for JavaScript as well (at least a short list of some of the must-read books).

**Comment by huei90** [comment]
Done
https://github.com/sorrycc/awesome-javascript/commit/6bbdc2b05f64ba32e6fc24cf470f8ff34598dbf0

Worth Reading

**Comment by pedropolisenso** [comment]
Hello Guys, whats up?
