### ISSUE TITLE
Awesome Dependency Injection?

### ISSUE THREAD

**Issue by freshgum-bubbles** [sorrycc/awesome-javascript#860]
Hello!  I like this project but wanted to make a quick suggestion: it might be
worth hosting a section for Dependency Injection libraries in JavaScript.
There are a ton of really cool ones: awilix, injection-js, and a few others like node-di & didi.

It's a really interesting area, and I feel it's been a bit unexplored by the `awesome-*`
projects so far.

*This is a slightly biased recommendation*: [`@typed-injector/injector`](https://github.com/freshgum-bubbles/typedi),
which I'm the sole developer of.  It's a re-implementation of Angular's DI system
in TypeScript, with stuff like a type-checked container, `@SkipSelf`, `@Optional`,
11 kB bundle, and loads of other cool stuff :-) It's a fork of TypeDI, which was abandoned.
Nearly got the documentation website finished for it.

**Comment by Ashe-reset** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by freshgum-bubbles** [comment]
> 这是来自QQ邮箱的假期自动回复邮件。   您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

Translated version:

> This is a holiday auto-response email from QQ mailbox.
>
> Hello, I am on vacation recently and cannot reply to your email personally. I will reply to you as soon as I can after the vacation.

Looks like your email setup is wrong.  Not sure how your reply figures as, from what I can see, you're not a collaborator or a contributor here.

**Comment by gokaygurcan** [comment]
Hi @freshgum-bubbles,

Feel free to create a new section and start adding relevant resources. This is an open source project. 

Only problem I see is that the given example is not meeting with the basic criteria. But if you think there're more relevant ones, adding them in to the list is only a PR away. 

Cheers,
G.
