### ISSUE TITLE
Issue: Vite Module Bundler Missing

### ISSUE THREAD

**Issue by Ssaava** [sorrycc/awesome-javascript#867]
I noticed that Vite, a fast build tool and development server for web projects, is not currently listed as a module bundler option in the project's documentation or configuration. Vite has gained popularity in the JavaScript ecosystem for its speed and simplicity.

I kindly request adding Vite as a supported module bundler option, as it offers significant advantages in terms of speed and development experience. This addition would provide users with more flexibility and choices when setting up their development environments.

Thank you for considering this request!

**Comment by gokaygurcan** [comment]
Hi @Ssaava,

Please create a PR by following the `Contribution Guidelines` and add Vite into its relevant block. 

Best,
G.
