### ISSUE TITLE
Add an Expo e-commerce complete project

### ISSUE THREAD

**Issue by huanghanzhilian** [sorrycc/awesome-javascript#880]
C-Shopping-RN APP

This is a complete App developed by React Native (Expo). It is a beautiful e-commerce shopping application.

## Use technology

- React Native
- Redux Toolkit
- RTK Query
- Expo Router
-NativeWind

App open source address: https://github.com/huanghanzhilian/c-shopping-rn
Full stack open source address: https://github.com/huanghanzhilian/c-shopping

**Comment by gokaygurcan** [comment]
Hi, 

If you believe this project covers the requirements, please create PR and we'll consider. 

Cheers,
G.

**Comment by huanghanzhilian** [comment]
Good teacher, thank you for reminding me
