### ISSUE TITLE
Classes are obsolete

### ISSUE THREAD

**Issue by ericelliott** [sorrycc/awesome-javascript#90]
See [The Two Pillars of JavaScript: How to Escape the 7th Circle of Hell](https://medium.com/javascript-scene/the-two-pillars-of-javascript-ee6f3281e7f3)

Stampit is a good example of [prototypal oo done right](https://github.com/ericelliott/stampit).

**Comment by huei90** [comment]
huh? What should I do on this?

**Comment by ericelliott** [comment]
I was suggesting the removal of links to class libraries because classes are obsolete, but now there's even better reason to remove them: JavaScript now has `class` built-in.

So the class libraries aren't just obsolete: they're redundant.
