### ISSUE TITLE
Need a bit of attention

### ISSUE THREAD

**Issue by kogarashisan** [sorrycc/awesome-javascript#98]
Hello to all project contributors!

My previous pull request is waiting for more than two months, so I want to ask someone to review it and include in your list.

First of all, i've just created [another pull request](https://github.com/sorrycc/awesome-javascript/pull/97) - it's my JavaScript class model, which comes with it's own high-quality speed comparison (in a [separate repository](https://github.com/kogarashisan/PerfTests)). I will add more frameworks soon.

ClassManager already gathered 24 stars, and uses rather unique method of inheritance, which makes it one of the fastest way to create classes in the world - it renames parent methods in child's prototype, and there is no prototype chain in inherited classes.

My [previous pull request](https://github.com/sorrycc/awesome-javascript/pull/84) is my framework, which deserves to stand near such frameworks as Angular and Ember. It's young, but it can already be considered as better alternative to these frameworks.

I ask someone to review my submissions and merge. If you have any questions - feel free to ask.

**Comment by huei90** [comment]
https://github.com/sorrycc/awesome-javascript/pull/97

**Comment by kogarashisan** [comment]
Thank You!

**Comment by kogarashisan** [comment]
Sorry for reopening, how about my framework, #84, will you accept it?
if you need to resolve merge conflicts - just tell.

**Comment by huei90** [comment]
Sure, but update the repo so that I can merge.

**Comment by kogarashisan** [comment]
Created a new request here: https://github.com/sorrycc/awesome-javascript/pull/131

**Comment by huei90** [comment]
done thanks @kogarashisan

**Comment by kogarashisan** [comment]
Thanks a lot!
